# Generated by Django 4.2.29 on 2026-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_follow_prevent_self"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
