# Generated by Django 4.2.29 on 2026-03-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_backfill_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stars",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
