# Generated by Django 4.2 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_profile_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="stars",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
